# Generated by Django 5.0.2 on 2024-02-14 05:41

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('post', models.ImageField(upload_to=post.models.post_directory_path)),
                ('likes', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
