# Generated by Django 5.0.2 on 2024-02-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_alter_friendship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='vrf_code',
            field=models.CharField(default='', max_length=32),
        ),
    ]
